batch_size: 64
fine_tune_from: /runs_ft/Aug14_13-07-51
log_every_n_steps: 50
gpu: cuda:0
data_name: 'matbench_dielectric'
task_type : 'regression'

model: 
  atom_fea_len: 64
  h_fea_len: 128
  n_conv: 3
  n_h: 1

dataset:
  fold_num: 1
  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2


dataloader:
  num_workers: 4


