batch_size: 256
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
gpu: cuda:1

optim:
  optimizer: Adam
  lr: 0.001
  weight_decay: 1e-5

model: 
  atom_fea_len: 256
  h_fea_len: 512
  n_conv: 3
  n_h: 1

dataset:
  root_dir: ../Self-Sup-Crystal/matminer
  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2
  random_seed: 666

dataloader:
  val_ratio: 0.05
  num_workers: 8

loss:
  temperature: 0.1
  use_cosine_similarity: True