batch_size: 256
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 1e-6
fp16_precision: False
init_lr: 0.001
gpu: cuda:2

model: 
  num_layer: 5
  emb_dim: 128
  feat_dim: 256
  JK: last
  drop_ratio: 0.0

dataset:
  num_workers: 4
  valid_size: 0.1
  test_size: 0.1
  data_dir: perovskites
  k: 12
