batch_size: 128
epochs: 50
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
gpu: cuda:3

optim:
  optimizer: Adam
  lr: 0.0005
  # momentum: 0.9
  weight_decay: 1e-5

model: 
  atom_fea_len: 256
  h_fea_len: 512
  n_conv: 5
  n_h: 1

dataset:
  root_dir: ../Self-Sup-Crystal/data/perovskites_cifs
  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2
  random_seed: 567

dataloader:
  train_ratio: None
  val_ratio: 0.1
  test_ratio: 0.1
  num_workers: 4
