batch_size: 16
epochs: 1
eval_every_n_epochs: 1
fine_tune_from: ./runs_ft/Feb14_12-00-49/
#./runs_contrast/Oct30_17-55-19
#./runs_contrast/Oct28_00-50-41
# fine_tune_from: runs_contrast/Apr21_18-05-12
log_every_n_steps: 50
gpu: cuda:3
#random_seed: 101

model: 
  atom_fea_len: 64
  h_fea_len: 128
  n_conv: 3
  n_h: 1

dataset:
  root_dir: perovskites
  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2


dataloader:
  num_workers: 4


