batch_size: 128
epochs: 1000
eval_every_n_epochs: 1
fine_tune_from: ./runs_contrast/Dec01_17-00-50
#./runs_contrast/Oct30_17-55-19
#./runs_contrast/Oct28_00-50-41
# fine_tune_from: runs_contrast/Apr21_18-05-12
log_every_n_steps: 50
gpu: cuda:0
random_seed: 1
data_name: 'matbench_phonons'
task_type : 'regression'

optim:
  optimizer: Adam
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-6

model: 
  atom_fea_len: 64
  h_fea_len: 128
  n_conv: 3
  n_h: 1

dataset:
  fold_num: 0
  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2


dataloader:
  num_workers: 4


